[[OSQP]]
arch = "aarch64"
git-tree-sha1 = "c5bc51b6230bd5c0d9ac4a70a89a298f7a99b50c"
libc = "glibc"
os = "linux"

    [[OSQP.download]]
    sha256 = "93c57bf7fd36c37293f36e1d72d427d1c8149d28badc766490952c34049e34d1"
    url = "https://github.com/JuliaBinaryWrappers/OSQP_jll.jl/releases/download/OSQP-v0.6.2+0/OSQP.v0.6.2.aarch64-linux-gnu.tar.gz"
[[OSQP]]
arch = "aarch64"
git-tree-sha1 = "f49f29588dbd98a6e9f559f1804e1a1c2ce2ed7d"
libc = "musl"
os = "linux"

    [[OSQP.download]]
    sha256 = "cea0d0ce128d7bae5ca679c3edb153305b4d1f4419f81a579db79dfe9b85e9e1"
    url = "https://github.com/JuliaBinaryWrappers/OSQP_jll.jl/releases/download/OSQP-v0.6.2+0/OSQP.v0.6.2.aarch64-linux-musl.tar.gz"
[[OSQP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d08874016b14437126731421c86db70c54b7bde8"
libc = "glibc"
os = "linux"

    [[OSQP.download]]
    sha256 = "25f22cdcf58c106797afaebe676db18c71d9ac806808d3cc08b53919511e4ed1"
    url = "https://github.com/JuliaBinaryWrappers/OSQP_jll.jl/releases/download/OSQP-v0.6.2+0/OSQP.v0.6.2.armv7l-linux-gnueabihf.tar.gz"
[[OSQP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9c8d439d5c44981fb9f244643bd3234d85239ff2"
libc = "musl"
os = "linux"

    [[OSQP.download]]
    sha256 = "511ff1974f471d8e5bc66ed7433bcedc40246c05e6aebc6ff6a369e05776a283"
    url = "https://github.com/JuliaBinaryWrappers/OSQP_jll.jl/releases/download/OSQP-v0.6.2+0/OSQP.v0.6.2.armv7l-linux-musleabihf.tar.gz"
[[OSQP]]
arch = "i686"
git-tree-sha1 = "3f48331aae5f58f4ed325d5cf1cbdddfbdde8f6e"
libc = "glibc"
os = "linux"

    [[OSQP.download]]
    sha256 = "c46f394223b334eec606dbf5712864e03cfafd54ad98df4e50da21ea591e3582"
    url = "https://github.com/JuliaBinaryWrappers/OSQP_jll.jl/releases/download/OSQP-v0.6.2+0/OSQP.v0.6.2.i686-linux-gnu.tar.gz"
[[OSQP]]
arch = "i686"
git-tree-sha1 = "c0990260843993d0f9f972b01052a4c683fbf44f"
libc = "musl"
os = "linux"

    [[OSQP.download]]
    sha256 = "db0ca4bb1110496af5f82a242e30afe2396ef3a995367e5133bf9f2e46caa5c7"
    url = "https://github.com/JuliaBinaryWrappers/OSQP_jll.jl/releases/download/OSQP-v0.6.2+0/OSQP.v0.6.2.i686-linux-musl.tar.gz"
[[OSQP]]
arch = "i686"
git-tree-sha1 = "672e3db7258802fd05e53d60fce23c77b94f1379"
os = "windows"

    [[OSQP.download]]
    sha256 = "0eaa202df481f1ae4a3613cda6e0b0caeb9e5fcc00cfdd89b45bf0a553d2ed9f"
    url = "https://github.com/JuliaBinaryWrappers/OSQP_jll.jl/releases/download/OSQP-v0.6.2+0/OSQP.v0.6.2.i686-w64-mingw32.tar.gz"
[[OSQP]]
arch = "powerpc64le"
git-tree-sha1 = "b5570361c0523e3d6d8adde9495e01eb7fcb9956"
libc = "glibc"
os = "linux"

    [[OSQP.download]]
    sha256 = "e466b5c93a05d1ff3a629184fc6e42ea3f8aff4c69fba7cc79641d7121d30471"
    url = "https://github.com/JuliaBinaryWrappers/OSQP_jll.jl/releases/download/OSQP-v0.6.2+0/OSQP.v0.6.2.powerpc64le-linux-gnu.tar.gz"
[[OSQP]]
arch = "x86_64"
git-tree-sha1 = "4cd25abdc06a3e3a076f6e7398ce34dc3db5f4f9"
os = "macos"

    [[OSQP.download]]
    sha256 = "68e45febd50991f9d147e4383f2e567c267c74defd09c7bac4d4234bc945b737"
    url = "https://github.com/JuliaBinaryWrappers/OSQP_jll.jl/releases/download/OSQP-v0.6.2+0/OSQP.v0.6.2.x86_64-apple-darwin.tar.gz"
[[OSQP]]
arch = "x86_64"
git-tree-sha1 = "af9a968d0bb665ab86b48fba1721cbcd7358e06e"
libc = "glibc"
os = "linux"

    [[OSQP.download]]
    sha256 = "1e8dabe6b6a608c464c93ab18e503042c10f0316884bcb08309adb4968efc6d2"
    url = "https://github.com/JuliaBinaryWrappers/OSQP_jll.jl/releases/download/OSQP-v0.6.2+0/OSQP.v0.6.2.x86_64-linux-gnu.tar.gz"
[[OSQP]]
arch = "x86_64"
git-tree-sha1 = "bc0bc475108775bb86cf3ab99f56d60913c00c30"
libc = "musl"
os = "linux"

    [[OSQP.download]]
    sha256 = "d07af642fffe0d222cb0eef6ca312abccc3c5b4161e1395448479e2daa7d4abc"
    url = "https://github.com/JuliaBinaryWrappers/OSQP_jll.jl/releases/download/OSQP-v0.6.2+0/OSQP.v0.6.2.x86_64-linux-musl.tar.gz"
[[OSQP]]
arch = "x86_64"
git-tree-sha1 = "1ce7ce2f388c61786a3234b0617e5e2921b6e15a"
os = "freebsd"

    [[OSQP.download]]
    sha256 = "0e44aa7f915ed10a58e6fef75884d8423d03b53f9a24c20a75e187336412e1a9"
    url = "https://github.com/JuliaBinaryWrappers/OSQP_jll.jl/releases/download/OSQP-v0.6.2+0/OSQP.v0.6.2.x86_64-unknown-freebsd.tar.gz"
[[OSQP]]
arch = "x86_64"
git-tree-sha1 = "4a70d5aba08f6e66f709d37b8565309bf3801713"
os = "windows"

    [[OSQP.download]]
    sha256 = "0adb4e084b7c9f3619bf82b2301a7494160359723a9231328accab34c47ce772"
    url = "https://github.com/JuliaBinaryWrappers/OSQP_jll.jl/releases/download/OSQP-v0.6.2+0/OSQP.v0.6.2.x86_64-w64-mingw32.tar.gz"
